# Generated by Django 5.0 on 2024-07-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_character_info_alter_profile_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='set',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_in_set', to='main.set'),
        ),
    ]
