# Generated by Django 5.0 on 2024-07-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_character_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.character'),
        ),
    ]
