# Generated by Django 5.0 on 2024-07-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='bundles_containing_set', to='main.set'),
        ),
        migrations.AlterField(
            model_name='character',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_profiles', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.character'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_in_set', to='main.set'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='sets_containing_item', to='main.item'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
